version: '3'
services:
  db:
    image: mongo
    container_name: db-mongo
    volumes:
      - data:/data/db
      - ./seed/seed.js:/docker-entrypoint-initdb.d/seed.js
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    command: sh -c "chmod +x ./docker-entrypoint-initdb.d/init-mongo.sh && sh ./docker-entrypoint-initdb.d/init-mongo.sh"

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: /app/app
    depends_on:
      - db

volumes:
  data:
